version: "3"
services:
  card-pokemon:
    build:
      dockerfile: ./dockerfile-angular
    image: card-pokemon
    privileged: true
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
  nginx:
    build:
      dockerfile: ./dockerfile-nginx
    image: card-pokemon-nginx
    privileged: true
    deploy:
      replicas: 1
    ports:
      - "80:80"
